# The TIA - Team!

trigger:
- '*'

schedules:
  - cron: "0 8 * * *"
    displayName: Schedule job
    branches:
      include:
      - main
    always: true

pool:
  vmImage: 'windows-latest'

jobs:
- job: LoadAgentNode1
  displayName: RPA
  continueOnError: false
  workspace:
    clean: all
  steps:
    - template: WorkerRPAJob.yml
