# The TIA - Team!
# Setup AiMaps environment with BrowserMobProxy
steps:

- task: Xther-Deployment@0  
  inputs:
    installDir: '$(Build.SourcesDirectory)/xther/'
    resources: 'CHR'
  displayName: 'XTher install'

- task: PowerShell@2
  inputs:    
    targetType: 'inline'
    script: |
      $destinationFolder = "$(Build.SourcesDirectory)/aimaps_full/Selenium/"
      if (!(Test-Path -path $destinationFolder)) {New-Item $destinationFolder -Type Directory}
      Copy-Item '$(Build.SourcesDirectory)/xther/*' $destinationFolder -Force -Recurse
  displayName: 'Setup drivers'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    workingDirectory: '$(Build.SourcesDirectory)/aimaps_full'
    script: |
        ./AiMap.Console.exe src="$(Build.SourcesDirectory)/maps/rpa__cluster.aiml" --VarVarsCluster.pipelineId="$(Build.BuildId)"
  displayName: 'Running bots'
  timeoutInMinutes: 5